import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

import { Playfair_Display, Inter } from 'next/font/google';

const playfair = Playfair_Display({ 
  subsets: ['latin'],
  variable: '--font-playfair',
});

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${playfair.variable} ${inter.variable} h-full antialiased`}
    >
      {/* overflow-x-hidden add kora hoyeche jate horizontal scroll na ashe */}
      <body className="min-h-full flex flex-col overflow-x-hidden">
        <Navbar />
        
        {/* 'max-w-7xl' ekhane bad dewa hoyeche jate Banner full width hote pare */}
        <main className="w-full flex-1">
          {children}
        </main>
        
        <Footer />
      </body>
    </html>
  );
}
